version: '3.1'

volumes:
  mysql_data: {}
  site_packages: {}

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fasttest
      - MYSQL_USER=fastuser
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - '3306'
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci]
    healthcheck:
      test: "mysqladmin -uroot -ppassword ping"
      interval: 3s
      timeout: 1s
      retries: 10

  fastapi:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile-dev
    command: /start-dev.sh
    volumes:
      - ./fastapi:/fastapi:cached
      - site_packages:/usr/local/lib/python3.9/site-packages/
    environment:
      - DEBUG=True
      - DEPLOYMENT_LEVEL=development
      - SERVER_NAME=fastapi
      - SERVER_HOST=fastapi
      - PROJECT_NAME=fastapi
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/fasttest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db


networks:
  default-network:
    driver: bridge